import Head from 'next/head'
import React from 'react'
import Nav from './Nav'

export default function Layout({ children }) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Nav>
                    {children}
                </Nav>
            </div>
        </>
    )
}
